sylius_grid:
    grids:
        sylius_admin_promotion:
            fields:
                afterTax:
                    type: twig
                    label: monsieurbiz_sylius_advanced_promotion.promotion.applied_after_tax
                    options:
                        template: "@SyliusUi/Grid/Field/yesNo.html.twig"
                channels:
                    type: twig
                    label: sylius.ui.channels
                    options:
                        template: '@SyliusAdmin/Grid/Field/_channels.html.twig'
            filters:
                afterTax:
                    type: boolean
                    label: monsieurbiz_sylius_advanced_promotion.promotion.applied_after_tax
