services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    MonsieurBiz\SyliusAdvancedPromotionPlugin\:
        resource: '../../*'
        exclude: '../../{Entity,Migrations}'

    MonsieurBiz\SyliusAdvancedPromotionPlugin\Controller\:
        resource: '../../Controller'
        tags: [ 'controller.service_arguments' ]

    MonsieurBiz\SyliusAdvancedPromotionPlugin\Promotion\Checker\Eligibility\:
        resource: '../../Promotion/Checker/Eligibility'
        tags: [ 'sylius.promotion_eligibility_checker' ]

